### ISSUE TITLE
Checklist for initial release

### ISSUE THREAD

**Issue by jborean93** [jborean93/pyspnego#2]
The following should be done before creating the actual `0.1.0` release on pypi

_Note: This list should be reset after ever release candidate is made_

- [x] Wheel can be installed and used on Windows Python 2.7 - 3.8 on vanilla Windows box
    * Done - Tested on Windows Server 2012 R2 and Windows Server 2008
- [x] [pypsrp](https://github.com/jborean93/pypsrp/pull/78) passing CI
- [x] [requests-credssp](https://github.com/jborean93/requests-credssp/pull/17) passing CI
- [x] [smbprotocol](https://github.com/jborean93/smbprotocol/pull/41) passing CI
- [x] [ntlm-auth](https://github.com/jborean93/ntlm-auth/commit/417db8b6fb0f9b5f86f314e257b8a4893f74c057) has been updated to point to this repo
- [x] [pypi landing page](https://pypi.org/project/pyspnego) has correct readme and information

WinRM Specific Checks

- [x] arcfour-hmac message encryption works
- [x] aes128-cts-hmac-sha1-96 message encryption works
- [x] credential delegation works
- [x] Test out channel binding tokens for edge cases

**Comment by jborean93** [comment]
I think I've done enough testing, will give [RC3](https://github.com/jborean93/pyspnego/releases/tag/v0.1.0rc3) a day before looking at cutting the real release. All downstream libraries I am planning on adding this to will work with the changes so far. The integration tests seem to cover a lot of the really edge cases I can think off but there's bound to be other problems. Will just have to deal with them as this is used more in the real world.

**Comment by jborean93** [comment]
Will need to wait until https://github.com/pythongssapi/python-gssapi/pull/218 is merged before finalising the `ok_as_delegate` code (and adding a test).

**Comment by jborean93** [comment]
Version 0.1.0 has been released https://pypi.org/project/pyspnego/.
